[package]
name = "xdialog"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "A small native-ish cross platform dialogs library with zero runtime dependencies."
authors = ["Caelan Sayler <git@caesay.com>"]
repository = "https://github.com/velopack/xdialog"
keywords = ["dialog", "message-box", "messagebox", "cross-platform", "webview", "webview2"]
categories = ["graphics", "gui", "visualization"]

[features]
default = ["fltk-bundled"]
fltk-bundled = ["fltk/fltk-bundled"]

[dependencies]
log = "0.4"
atomic-counter = "1.0"
lazy_static = "1.5"
enum-map = "2.7"
urlencoding = "2.1.3"
oneshot = "0.1.8"
thiserror = "2.0"
winit = "0.30"
wry = "0.47"
dpi = "0.1"

# windows native
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_Controls",
] }
widestring = "1.1.0"

# fltk
fltk = "1.4"
font-kit = "0.14"
dark-light = "1.1"
mina = "0.1"

# xaml islands
# [dependencies.windows]
# version = ">= 0.30, <= 0.35"
# features = [
#     "alloc",
#     "Win32_Foundation",
#     "Win32_UI_WindowsAndMessaging",
#     "Win32_System_WinRT_Xaml",
#     "UI_Xaml_Hosting",
#     "UI_Xaml_Controls",
#     "UI_Xaml_Markup",
#     "UI_Xaml",
# ]

[dev-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[build-dependencies]
winres = "0.1"
cc = "1"
